### PR TITLE
Adds @zachallaun's test framework as submodule

### LINKED ISSUE #18: Unit testing framework
It would be awesome if someone would take a day or two to create something simple so that we can start building a test suite.

### PR DESCRIPTION
**Pull request by despeset**
For future testing fun! Closes #18 

Are people into this?

### CODE REVIEW

**Comment by zachallaun** [comment]
See [zachallaun/DeFacto](https://github.com/zachallaun/DeFacto).

**Comment by despeset** [comment]
I want to see one example of a fully working test for something we've already implemented before we pull this into master so that there is a clear path forward for testing everything.

**Comment by despeset** [comment]
But I am _super_ into actually being able to test all this stuff – especially before we start seriously bulking up on middleware for our default stack ( see #14, #22,  #15)

**Comment by zachallaun** [comment]
It seems like this could be used to very easily test middleware, which is basically data transformation. Super stateful and blocking stuff is obviously much more difficult.

I'll try to push an example tomorrow, but I may not get around to it. If anyone has the time to take a crack at it, go ahead.

**Comment by despeset** [comment]
This is now a Julia package called `FactCheck` – we should use the REQUIRE methodology to use the package instead of submodules.

**Pull request closed without merging**
