### PR TITLE
Don't merge: Circular Dependency issue

### PR DESCRIPTION
**Pull request by astrieanna**
I want the websockets example/user code to not have to explicitly call the websockets handshake function.
This means that the Http server would call it before calling the application's websocket handler.
Websockets uses the Http Request type, in order to do the Handshake.
This creates a circular dependency.

Solution Options:
1) Websockets and Http should be one thing, so they can full depend on each other
2) Websockets should not depend on Http Request: just have Http hand it the required headers.
3) Http should not depend on Websockets... some way of making the websocket constructors/handler do this automatically....

Any opinions on how to solve this?

### CODE REVIEW

**Comment by chuckha** [comment]
I need the HttpRequest type for the Requests module I'm building. Perhaps that should be abstracted out to its own module so we can include it when necessary.

**Comment by despeset** [comment]
I just made another pull request that solves this issue in a different way -- by preserving all the existing dependencies but moving the definition of `WebsocketHandler` to `Websockets.jl` and renaming the previous `WebsocketHandler` type used in `Http.jl` to `WebsocketClientHandler` under the hood.  This preserves our original API and ( I think? ) achieves the goals stated above.

I think abstracting the HttpRequest type out to a different module should be considered a different issue.

**Comment by astrieanna** [comment]
Your version does solve the problem and preserve the API, but I'd really like to express this with types.

If, in your version, I get a bit confused and call WebsocketClientHandler's constructor directly, then it just won't work and I'll be very confused. It would probably complain about trying to call read or write on Http's Client type. (which is what gets passed into the WebsocketHandler rather than a WebSocket).

It would be better if it were impossible to make a WebsocketHandler without setting up the handshake part. One way is for the Http stuff to call the handshake function explicitly; moving HttpRequest into it's own module seems like a reasonable way to achieve this. Any way that makes Http's WebsocketHandler type actually relate to WebSockets would also require this change.

Also, why don't the functions inside WebsocketHandler/HttpHandler types have types? There must be some way to write "Function(Http.Request, Http.Client) -> Any" in Julia. And then the type signature could form a useful piece of documentation.

**Comment by despeset** [comment]
I'm all for finding a way to express this using types, as long as we can maintain as decoupled an implementation of each module as possible. Having the http code perform the handshake seems suspect to me because it feels like it would need to know too much about websockets. 

Another option would be to add a new field like 'handshake' to WebsocketHandler that the http code would call. Then the websockets code could define the handler-only constructor method and supply the handshake...

**Comment by astrieanna** [comment]
I mean, it's already pretty websockets specific -- it is called a "WebsocketsHandler".
This would required the Http stuff to know that "websockets consists of calling a specific (handshake) function always, and then the application-specific handler function".

Adding "handshake" as a field to WebsocketHandler doesn't actually decouple them more as far as I can tell? The Http stuff still has to call a "handshake" function.
Websockets always has the same handshake. I guess it might change if you wanted to refuse some connections immediately based on.... source or path or something? But that's kind of similar to just immediately closing them.

**Comment by zachallaun** [comment]
My thought is that all implementation-agnostic code and types (`Request`, `Response`, `Headers`, et al.) should be pulled into another module called `Httplib` or something. @ChuckHa's requests and @astrieanna's websockets modules could depend on it without having to know about `Http`.

**Comment by despeset** [comment]
Works for me :+1:

**Comment by astrieanna** [comment]
I agree. The current `Http` module is mixing the details of the Http protocol (what @zachallaun suggests should be in `Httplib`) with the code that handles Tcp connections and dispatches them to the handlers.
Maybe `Http` should be split into `Server` (dispatches to http/websockets handlers) and `Httplib`/`HttpLib` (has the types/etc to represent the Http protocol details, the way Websockets handles the details of Websockets).

The "is it websockets" test should also move to Websockets.

**Comment by despeset** [comment]
Closed by 103fda1431cec4e9b8f462a661b5b53930a05570

**Pull request closed without merging**
